### ISSUE TITLE
Possible apps to add

### ISSUE THREAD

**Issue by isabolaa** [ikkxeer/PSCacheCleaner#24]
- It would be a good idea to add either the most popular apps from the Adobe suite, or all of them.
- Add Opera since it a frequently used web browser too.
- WhatsApp too could be an option.
- Netflix.

**Comment by ikkxeer** [comment]
Hello `isabolaa`,

First of all, I wanted to thank you for your involvement in the project and for your suggestions. Continuing with it, here I bring a response to all your suggestions:
1. **Adobe Suite:**
- Photoshop has already been added! ✅
- Adobe Illustrator is mostly saved in %temp%! ✅
- The rest are in development...  👌
2. Resolved! Implemented in version 2.4. ✅
3. In this case, I would not touch the WhatsApp cache files, in addition to the fact that with the new versions the folders are quite hidden, it would not be very useful due to the little use of its desktop application compared to the popular Whatsapp Web. I saved the option for future versions! 👌
4. Same as point 3 👌

Stay tuned for project updates to find out when the new versions will be applied with your suggestions applied! 😁

![ItsFineDogFineGIF](https://github.com/ikkxeer/PSCacheCleaner/assets/137718457/ef5e35f7-cb1a-4ee4-a565-80aba968752a)
